name: Node Checks
description: Run checks for Node.js projects

inputs:
  check-type:
    description: Type of check to run (format, lint, test, types)
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Check Formatting
      if: inputs.check-type == 'format'
      run: npm run format

    - name: Run Linting
      if: inputs.check-type == 'lint'
      env:
          NODE_OPTIONS: --max-old-space-size=4096 # Increase memory to 4GB
      run: npm run lint

    - name: Run Tests
      if: inputs.check-type == 'test'
      run: npm run test

    - name: Run Type Checking
      if: inputs.check-type == 'types'
      run: npm run check
