name: Node Checks
description: Run checks for Node.js projects

inputs:
  check-type:
    description: Type of check to run (format, lint, test, types)
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: "20"
        cache: "npm"

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Check Formatting
      if: inputs.check-type == 'format'
      shell: bash
      run: npm run format

    - name: Get changed files
      if: inputs.check-type == 'lint' # linting OOMs on CI, so only run on changed files
      id: changed-files
      uses: tj-actions/changed-files@v47

    - name: Run Linting
      if: inputs.check-type == 'lint'
      env:
        NODE_OPTIONS: --max-old-space-size=8192 # Increase memory to avoid OOM
      shell: bash
      run: npm run lint -- ${{ steps.changed-files.outputs.all_changed_files }}

    - name: Install Playwright Browsers
      if: inputs.check-type == 'test'
      shell: bash
      run: npx playwright install --with-deps

    - name: Run Tests
      if: inputs.check-type == 'test'
      shell: bash
      run: npm run test

    - name: Run Type Checking
      if: inputs.check-type == 'types'
      shell: bash
      run: npm run check
